openapi: 3.0.0
info:
  version: 0.0.1
  title: diagnostic-au-ghm
paths:
  '/diagnostic/{code}/acts':
    x-swagger-router-controller: Diagnostic
    get:
      tags:
        - Diagnostic
      description: Get ACTs details by Diagnostic code.
      operationId: getACTsByDiagnosticCode
      parameters:
        - name: code
          in: path
          description: The Diagnostic code of acts.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicalActsResponse'
        '403':
          description: Error Occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
  /diagnostic:
    x-swagger-router-controller: Diagnostic
    post:
      tags:
        - Diagnostic
      description: Diagnostic a GHM by decision tree making algorithm.
      operationId: diagnosticGHM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosticResponse'
        '403':
          description: Error Occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiagnosticRequest'
        description: The object contains diagnostic request.
        required: true
      x-code-samples:
        - lang: CURL
          source: |
            curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"clientParameters":{"age": 28,"session": 1}' 'https://localhost:3000/diagnostic'
  '/ghms/{code}':
    x-swagger-router-controller: GHMs
    get:
      tags:
        - GHMs
      description: Get GHM details by GHM code.
      operationId: getGHMByCode
      parameters:
        - name: code
          in: path
          description: The GHM code of a GHM.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GHMResponse'
        '403':
          description: Error Occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsResponse'
servers:
  - url: /
components:
  schemas:
    DiagnosticRequest:
      properties:
        clientParameters:
          type: object
          properties:
            age:
              type: integer
            sessions:
              type: integer
            gender:
              type: string
          description: The client's information
        mainDiagnosis:
          type: string
          example: CMD-28
          description: The main category diagnosis code
        associatedDiagnoses:
          type: array
          items:
            type: string
          example:
            - D-145
            - D-114
    DiagnosticResponse:
      properties:
        associatedDiagnoses:
          type: array
          items:
            type: string
          example:
            - D-113
            - D-114
            - D-063
            - D-142
            - D-143
        possibleGHMCodes:
          type: array
          items:
            type: string
          example:
            - 28Z01
            - 28Z02
            - 28Z03
            - 28Z04
            - 90Z02Z
          description: The all possible GHMs
    MedicalActsResponse:
      properties:
        medicalActs:
          type: array
          items:
            type: object
          example:
            - code: A-112
              descripton: ''
            - code: A-113
              descripton: ''
            - code: A-114
              descripton: ''
    GHMResponse:
      properties:
        code:
          type: string
          description: The GHM code
          example: 28Z16
        name:
          type: string
          description: The GHM description
          example: Seasen d aphérèse sanguine (D-054)
        severity:
          type: integer
          description: The severity of GHM
          example: 1
    ErrorsResponse:
      required:
        - code
      properties:
        code:
          type: string
        message:
          type: string
